#' Synthetic ClockSHAP example dataset
#'
#' A small, fully synthetic dataset used in the package examples and vignette.
#' It contains a cohort of 120 samples with eight genes carrying genuine linear
#' age trends, plus a ridge-fit linear clock that predicts age from those genes.
#' Two samples are planted deviators: \code{S001} reads older than expected for
#' its age and \code{S002} reads younger, both driven by a shared
#' senescence / inflammaging axis (\code{CDKN2A}, \code{GDF15}, \code{IL6}).
#'
#' @format A list with three elements:
#' \describe{
#'   \item{\code{features}}{A 120 x 8 numeric matrix of synthetic gene
#'     expression. Rows are samples (\code{S001}-\code{S120}); columns are genes
#'     (\code{CDKN2A}, \code{GDF15}, \code{EDA2R}, \code{IL6}, \code{LMNB1},
#'     \code{ELN}, \code{COL1A1}, \code{FOXO3}).}
#'   \item{\code{age}}{Numeric vector of length 120, chronological age in years.}
#'   \item{\code{clock}}{A \code{linear_clock} object (intercept, per-gene
#'     weights, centering and scaling) fit by ridge regression so predicted age
#'     tracks chronological age with realistic regression to the mean
#'     (slope < 1).}
#' }
#'
#' @details The data are entirely synthetic and carry no real biological signal;
#'   gene symbols are used only to make the example legible. Regenerated by
#'   \code{data-raw/make_clockshap_example.R}.
#'
#' @examples
#' ref <- fit_reference_profile(
#'   features = as.data.frame(clockshap_example$features),
#'   age      = clockshap_example$age
#' )
#' cs <- clockshap(
#'   features  = clockshap_example$features,
#'   age       = clockshap_example$age,
#'   clock     = clockshap_example$clock,
#'   reference = ref
#' )
#' cs$deviation
"clockshap_example"
